### 미니프로젝트 1
- 공공데이터 기반 지역별 통계 분석

In [24]:
# 주민등록 인구수중애서 충청남도만 전처리 후 csv파일로 저장 
import pandas as pd

conn_df = pd.read_csv('../data/raw/행정안전부_지역별&#40;행정동&#41; 성별 연령별 주민등록 인구수_20260630.csv', encoding='utf-8')
chu_conn_df = conn_df.query('시도명 == "충청남도"')
chu_conn_df.to_csv('chu_conn_df.csv',index=False, encoding='utf-8')

In [25]:
base_df = pd.read_csv('../data/raw/소상공인시장진흥공단_상가(상권)정보_충남_202603.csv')

/var/folders/hp/7dd90dfd5990g77b84z59cdr0000gn/T/ipykernel_58472/3479076987.py:1: DtypeWarning: Columns (0: 층정보) have mixed types. Specify dtype option on import or set low_memory=False.
  base_df = pd.read_csv('../data/raw/소상공인시장진흥공단_상가(상권)정보_충남_202603.csv')

In [26]:
list(base_df.columns)

['상가업소번호',
 '상호명',
 '지점명',
 '상권업종대분류코드',
 '상권업종대분류명',
 '상권업종중분류코드',
 '상권업종중분류명',
 '상권업종소분류코드',
 '상권업종소분류명',
 '표준산업분류코드',
 '표준산업분류명',
 '시도코드',
 '시도명',
 '시군구코드',
 '시군구명',
 '행정동코드',
 '행정동명',
 '법정동코드',
 '법정동명',
 '지번코드',
 '대지구분코드',
 '대지구분명',
 '지번본번지',
 '지번부번지',
 '지번주소',
 '도로명코드',
 '도로명',
 '건물본번지',
 '건물부번지',
 '건물관리번호',
 '건물명',
 '도로명주소',
 '구우편번호',
 '신우편번호',
 '동정보',
 '층정보',
 '호정보',
 '경도',
 '위도']

In [27]:
list(chu_conn_df.columns)

['행정기관코드',
 '기준연월',
 '시도명',
 '시군구명',
 '읍면동명',
 '계',
 '남자',
 '여자',
 '0세남자',
 '1세남자',
 '2세남자',
 '3세남자',
 '4세남자',
 '5세남자',
 '6세남자',
 '7세남자',
 '8세남자',
 '9세남자',
 '10세남자',
 '11세남자',
 '12세남자',
 '13세남자',
 '14세남자',
 '15세남자',
 '16세남자',
 '17세남자',
 '18세남자',
 '19세남자',
 '20세남자',
 '21세남자',
 '22세남자',
 '23세남자',
 '24세남자',
 '25세남자',
 '26세남자',
 '27세남자',
 '28세남자',
 '29세남자',
 '30세남자',
 '31세남자',
 '32세남자',
 '33세남자',
 '34세남자',
 '35세남자',
 '36세남자',
 '37세남자',
 '38세남자',
 '39세남자',
 '40세남자',
 '41세남자',
 '42세남자',
 '43세남자',
 '44세남자',
 '45세남자',
 '46세남자',
 '47세남자',
 '48세남자',
 '49세남자',
 '50세남자',
 '51세남자',
 '52세남자',
 '53세남자',
 '54세남자',
 '55세남자',
 '56세남자',
 '57세남자',
 '58세남자',
 '59세남자',
 '60세남자',
 '61세남자',
 '62세남자',
 '63세남자',
 '64세남자',
 '65세남자',
 '66세남자',
 '67세남자',
 '68세남자',
 '69세남자',
 '70세남자',
 '71세남자',
 '72세남자',
 '73세남자',
 '74세남자',
 '75세남자',
 '76세남자',
 '77세남자',
 '78세남자',
 '79세남자',
 '80세남자',
 '81세남자',
 '82세남자',
 '83세남자',
 '84세남자',
 '85세남자',
 '86세남자',
 '87세남자',
 '88세남자',
 '89세남자',
 '90세남자',
 '91세남자',
 '92세남자',
 '93세남자',
 '94세남자',
 '95세남자',
 '96세남자',
 '97세남자',
 '98세남자',
 '99세남자',
 '100세남자',
 '101세남자',
 '102세남자',
 '103세남자',
 '104세남자',
 '105세남자',
 '106세남자',
 '107세남자',
 '108세남자',
 '109세남자',
 '110세이상 남자',
 '0세여자',
 '1세여자',
 '2세여자',
 '3세여자',
 '4세여자',
 '5세여자',
 '6세여자',
 '7세여자',
 '8세여자',
 '9세여자',
 '10세여자',
 '11세여자',
 '12세여자',
 '13세여자',
 '14세여자',
 '15세여자',
 '16세여자',
 '17세여자',
 '18세여자',
 '19세여자',
 '20세여자',
 '21세여자',
 '22세여자',
 '23세여자',
 '24세여자',
 '25세여자',
 '26세여자',
 '27세여자',
 '28세여자',
 '29세여자',
 '30세여자',
 '31세여자',
 '32세여자',
 '33세여자',
 '34세여자',
 '35세여자',
 '36세여자',
 '37세여자',
 '38세여자',
 '39세여자',
 '40세여자',
 '41세여자',
 '42세여자',
 '43세여자',
 '44세여자',
 '45세여자',
 '46세여자',
 '47세여자',
 '48세여자',
 '49세여자',
 '50세여자',
 '51세여자',
 '52세여자',
 '53세여자',
 '54세여자',
 '55세여자',
 '56세여자',
 '57세여자',
 '58세여자',
 '59세여자',
 '60세여자',
 '61세여자',
 '62세여자',
 '63세여자',
 '64세여자',
 '65세여자',
 '66세여자',
 '67세여자',
 '68세여자',
 '69세여자',
 '70세여자',
 '71세여자',
 '72세여자',
 '73세여자',
 '74세여자',
 '75세여자',
 '76세여자',
 '77세여자',
 '78세여자',
 '79세여자',
 '80세여자',
 '81세여자',
 '82세여자',
 '83세여자',
 '84세여자',
 '85세여자',
 '86세여자',
 '87세여자',
 '88세여자',
 '89세여자',
 '90세여자',
 '91세여자',
 '92세여자',
 '93세여자',
 '94세여자',
 '95세여자',
 '96세여자',
 '97세여자',
 '98세여자',
 '99세여자',
 '100세여자',
 '101세여자',
 '102세여자',
 '103세여자',
 '104세여자',
 '105세여자',
 '106세여자',
 '107세여자',
 '108세여자',
 '109세여자',
 '110세이상 여자']

In [28]:
print(base_df[['시도명', '시군구명', '행정동명']].head())
print(chu_conn_df[['시도명', '시군구명', '읍면동명']].head())

    시도명     시군구명 행정동명
0  충청남도      공주시  의당면
1  충청남도      홍성군  홍성읍
2  충청남도      서천군   서면
3  충청남도  천안시 동남구  문성동
4  충청남도      홍성군  홍성읍
       시도명     시군구명 읍면동명
1961  충청남도  천안시 동남구  목천읍
1962  충청남도  천안시 동남구  풍세면
1963  충청남도  천안시 동남구  광덕면
1964  충청남도  천안시 동남구   북면
1965  충청남도  천안시 동남구  성남면

In [29]:
test_merge = pd.merge(
    base_df, chu_conn_df, 
    left_on = ['시도명', '시군구명'], 
    right_on = ['시도명','시군구명'])
test_merge

,상가업소번호,상호명,지점명,상권업종대분류코드,상권업종대분류명,상권업종중분류코드,상권업종중분류명,상권업종소분류코드,상권업종소분류명,표준산업분류코드,...,101세여자,102세여자,103세여자,104세여자,105세여자,106세여자,107세여자,108세여자,109세여자,110세이상 여자
0,MA010120220805873077,돈우,NaN,I2,음식,I201,한식,I20107,돼지고기 구이/찜,I56113,...,0,1,0,0,0,0,0,0,0,0
1,MA010120220805873077,돈우,NaN,I2,음식,I201,한식,I20107,돼지고기 구이/찜,I56113,...,0,0,0,0,0,0,0,0,0,0
2,MA010120220805873077,돈우,NaN,I2,음식,I201,한식,I20107,돼지고기 구이/찜,I56113,...,1,0,2,0,0,0,0,0,0,0
3,MA010120220805873077,돈우,NaN,I2,음식,I201,한식,I20107,돼지고기 구이/찜,I56113,...,0,0,1,0,0,0,0,0,0,0
4,MA010120220805873077,돈우,NaN,I2,음식,I201,한식,I20107,돼지고기 구이/찜,I56113,...,0,0,1,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1762338,MA0106202601A1719910,시드니모터스,NaN,S2,수리·개인,S203,자동차 수리·세차,S20302,자동차 세차장,S95213,...,1,0,0,1,0,0,0,0,0,0
1762339,MA0106202601A1719910,시드니모터스,NaN,S2,수리·개인,S203,자동차 수리·세차,S20302,자동차 세차장,S95213,...,1,0,0,0,0,0,0,0,0,0
1762340,MA0106202601A1719910,시드니모터스,NaN,S2,수리·개인,S203,자동차 수리·세차,S20302,자동차 세차장,S95213,...,0,0,1,1,0,0,0,0,0,0
1762341,MA0106202601A1719910,시드니모터스,NaN,S2,수리·개인,S203,자동차 수리·세차,S20302,자동차 세차장,S95213,...,1,0,0,1,0,0,0,0,0,0
1762342,MA0106202601A1719910,시드니모터스,NaN,S2,수리·개인,S203,자동차 수리·세차,S20302,자동차 세차장,S95213,...,0,0,0,0,0,0,0,0,0,0

In [30]:
test_concat = pd.concat([base_df, chu_conn_df], join='inner')
test_concat

       시도명     시군구명
0     충청남도      공주시
1     충청남도      홍성군
2     충청남도      서천군
3     충청남도  천안시 동남구
4     충청남도      홍성군
...    ...      ...
2166  충청남도      태안군
2167  충청남도      태안군
2168  충청남도      태안군
2169  충청남도      태안군
2170  충청남도      태안군

[122036 rows x 2 columns]

In [31]:
base_df['시군구명'].unique()

<StringArray>
[    '공주시',     '홍성군',     '서천군', '천안시 동남구',     '서산시',     '논산시',     '아산시',
 '천안시 서북구',     '보령시',     '당진시',     '금산군',     '예산군',     '태안군',     '부여군',
     '청양군',     '계룡시']
Length: 16, dtype: str

In [32]:
chu_conn_df['시군구명'].unique()

<StringArray>
['천안시 동남구', '천안시 서북구',     '공주시',     '보령시',     '아산시',     '서산시',     '논산시',
     '계룡시',     '당진시',     '금산군',     '부여군',     '서천군',     '청양군',     '홍성군',
     '예산군',     '태안군']
Length: 16, dtype: str

In [33]:
chu_conn_df['시군구명'] = chu_conn_df['시군구명'].replace({
    '천안시 동남구':'천안시', 
    '천안시 서북구':'천안시'
})

In [34]:
chu_conn_df.to_csv(
    '../data/processed/chu_conn_df.csv',
    index=False,
    encoding='utf-8-sig'
)

In [35]:
base_ch_df = base_df.copy()

base_ch_df['시군구명'] = base_ch_df['시군구명'].replace({
    '천안시 동남구': '천안시',
    '천안시 서북구': '천안시'
})

In [36]:
print('인구 데이터 중복:', chu_conn_df.duplicated().sum())
print('상가 데이터 중복:', base_ch_df.duplicated().sum())

인구 데이터 중복: 0
상가 데이터 중복: 0

In [37]:
print(base_ch_df.columns)

Index(['상가업소번호', '상호명', '지점명', '상권업종대분류코드', '상권업종대분류명', '상권업종중분류코드',
       '상권업종중분류명', '상권업종소분류코드', '상권업종소분류명', '표준산업분류코드', '표준산업분류명', '시도코드',
       '시도명', '시군구코드', '시군구명', '행정동코드', '행정동명', '법정동코드', '법정동명', '지번코드',
       '대지구분코드', '대지구분명', '지번본번지', '지번부번지', '지번주소', '도로명코드', '도로명', '건물본번지',
       '건물부번지', '건물관리번호', '건물명', '도로명주소', '구우편번호', '신우편번호', '동정보', '층정보',
       '호정보', '경도', '위도'],
      dtype='str')

In [38]:
m_col = [f'{i}세남자' for i in range(110)] + ['110세이상 남자']
popum_conn_df = chu_conn_df.melt( 
    id_vars= ['시도명','시군구명', '읍면동명'],
    value_vars= m_col,
    var_name='나이',
    value_name='남자 인구수'
)
popum_conn_df

        시도명 시군구명 읍면동명         나이  남자 인구수
0      충청남도  천안시  목천읍       0세남자      22
1      충청남도  천안시  풍세면       0세남자      54
2      충청남도  천안시  광덕면       0세남자       3
3      충청남도  천안시   북면       0세남자       6
4      충청남도  천안시  성남면       0세남자       0
...     ...  ...  ...        ...     ...
23305  충청남도  태안군   남면  110세이상 남자       0
23306  충청남도  태안군  근흥면  110세이상 남자       0
23307  충청남도  태안군  소원면  110세이상 남자       0
23308  충청남도  태안군  원북면  110세이상 남자       0
23309  충청남도  태안군  이원면  110세이상 남자       0

[23310 rows x 5 columns]

In [39]:
f_col = [f'{i}세여자' for i in range(110)] + ['110세이상 여자']
popuf_conn_df = chu_conn_df.melt( 
    id_vars= ['시도명','시군구명', '읍면동명'],
    value_vars= f_col,
    var_name='나이',
    value_name='여자 인구수'
)
popuf_conn_df

        시도명 시군구명 읍면동명         나이  여자 인구수
0      충청남도  천안시  목천읍       0세여자      12
1      충청남도  천안시  풍세면       0세여자      44
2      충청남도  천안시  광덕면       0세여자       2
3      충청남도  천안시   북면       0세여자       2
4      충청남도  천안시  성남면       0세여자       2
...     ...  ...  ...        ...     ...
23305  충청남도  태안군   남면  110세이상 여자       0
23306  충청남도  태안군  근흥면  110세이상 여자       0
23307  충청남도  태안군  소원면  110세이상 여자       0
23308  충청남도  태안군  원북면  110세이상 여자       0
23309  충청남도  태안군  이원면  110세이상 여자       0

[23310 rows x 5 columns]

In [40]:
df_concat = pd.concat([popum_conn_df, popuf_conn_df], axis=1)
df_concat

        시도명 시군구명 읍면동명         나이  남자 인구수   시도명 시군구명 읍면동명         나이  여자 인구수
0      충청남도  천안시  목천읍       0세남자      22  충청남도  천안시  목천읍       0세여자      12
1      충청남도  천안시  풍세면       0세남자      54  충청남도  천안시  풍세면       0세여자      44
2      충청남도  천안시  광덕면       0세남자       3  충청남도  천안시  광덕면       0세여자       2
3      충청남도  천안시   북면       0세남자       6  충청남도  천안시   북면       0세여자       2
4      충청남도  천안시  성남면       0세남자       0  충청남도  천안시  성남면       0세여자       2
...     ...  ...  ...        ...     ...   ...  ...  ...        ...     ...
23305  충청남도  태안군   남면  110세이상 남자       0  충청남도  태안군   남면  110세이상 여자       0
23306  충청남도  태안군  근흥면  110세이상 남자       0  충청남도  태안군  근흥면  110세이상 여자       0
23307  충청남도  태안군  소원면  110세이상 남자       0  충청남도  태안군  소원면  110세이상 여자       0
23308  충청남도  태안군  원북면  110세이상 남자       0  충청남도  태안군  원북면  110세이상 여자       0
23309  충청남도  태안군  이원면  110세이상 남자       0  충청남도  태안군  이원면  110세이상 여자       0

[23310 rows x 10 columns]

In [41]:
he_conn_df = pd.concat(
    [popum_conn_df, popuf_conn_df['여자 인구수']], 
    axis=1)
he_conn_df['나이'] = (
    he_conn_df['나이']
    .str.replace('세이상 남자', '', regex=False)
    .str.replace('세남자', '', regex=False)
    .astype(int)
)
he_conn_df

        시도명 시군구명 읍면동명   나이  남자 인구수  여자 인구수
0      충청남도  천안시  목천읍    0      22      12
1      충청남도  천안시  풍세면    0      54      44
2      충청남도  천안시  광덕면    0       3       2
3      충청남도  천안시   북면    0       6       2
4      충청남도  천안시  성남면    0       0       2
...     ...  ...  ...  ...     ...     ...
23305  충청남도  태안군   남면  110       0       0
23306  충청남도  태안군  근흥면  110       0       0
23307  충청남도  태안군  소원면  110       0       0
23308  충청남도  태안군  원북면  110       0       0
23309  충청남도  태안군  이원면  110       0       0

[23310 rows x 6 columns]

In [42]:
he_conn_df.to_csv(
    '../data/processed/he_conn_df.csv',
    index=False
)

In [43]:
base_df[['법정동명', '행정동명']].head()

  법정동명 행정동명
0  의당면  의당면
1  홍성읍  홍성읍
2   서면   서면
3  문화동  문성동
4  홍성읍  홍성읍

In [44]:
# maria DB 에 store_csv 파일 연결 

import pandas as pd
import pymysql
import os
import numpy as np
from dotenv import load_dotenv

load_dotenv()


store_df = pd.read_csv('../data/processed/base_df.csv', encoding='utf-8')
conn = pymysql.connect(
        host = os.environ.get('DB_HOST'),
        port = int (os.environ.get('DB_PORT', 3306)),
        user=os.environ.get('DB_USER'),
        password=os.environ.get ('DB_PASSWORD'),
        database=os.environ.get ('DB_NAME'),
        charset='utf8mb4' )
sql = """
INSERT INTO tb_store(
    store_id,
    store_name,
    branch_name,
    category_large,
    category_medium,
    category_small,
    province_name,
    city_name,
    district_name)
VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s)
"""

store_df = store_df.replace({np.nan: None}) #NaN을 None으로 변환

data = store_df[[
    '상가업소번호',
    '상호명',
    '지점명',
    '상권업종대분류명',
    '상권업종중분류명',
    '상권업종소분류명',
    '시도명',
    '시군구명',
    '행정동명'
]].values.tolist()



with conn.cursor() as cur:
    cur.executemany(sql, data)

conn.commit()
# conn.close()

/var/folders/hp/7dd90dfd5990g77b84z59cdr0000gn/T/ipykernel_58472/1524330703.py:12: DtypeWarning: Columns (0: 층정보) have mixed types. Specify dtype option on import or set low_memory=False.
  store_df = pd.read_csv('../data/processed/base_df.csv', encoding='utf-8')

IntegrityError: (1062, "Duplicate entry 'MA010120220805873077' for key 'PRIMARY'")

In [ ]:
# maria DB 에 store_csv 파일 연결 

import pandas as pd
import pymysql
import os
import numpy as np
from dotenv import load_dotenv

load_dotenv()


population_df = pd.read_csv('../data/processed/he_conn_df.csv', encoding='utf-8')
conn = pymysql.connect(
        host = os.environ.get('DB_HOST'),
        port = int (os.environ.get('DB_PORT', 3306)),
        user=os.environ.get('DB_USER'),
        password=os.environ.get ('DB_PASSWORD'),
        database=os.environ.get ('DB_NAME'),
        charset='utf8mb4' )
sql = """
INSERT INTO tb_population(
    province_name,
    city_name,
    district_name,
    age,
    male_population,
    female_population)
VALUES (%s, %s, %s, %s, %s, %s)
"""

population_df = population_df.replace({np.nan: None}) #NaN을 None으로 변환

data = population_df[[
    '시도명',
    '시군구명',
    '읍면동명',
    '나이',
    '남자 인구수',
    '여자 인구수'
]].values.tolist()



with conn.cursor() as cur:
    cur.executemany(sql, data)

conn.commit()
# conn.close()

In [45]:
# 파생 지표 계산
store_df = pd.read_csv('../data/processed/base_df.csv', encoding='utf-8')
population_df = pd.read_csv('../data/processed/he_conn_df.csv', encoding='utf-8')

store_group = store_df.groupby('시군구명').size()
#store_group
population_df['총 인구수'] = population_df['남자 인구수'] + population_df['여자 인구수']
population_group = population_df.groupby('시군구명')['총 인구수'].sum()
df_concat_sp = pd.concat([store_group, population_group], axis=1)
df_concat_sp.columns = ['지역별 상가수', '지역별 인구수']

/var/folders/hp/7dd90dfd5990g77b84z59cdr0000gn/T/ipykernel_58472/1700152364.py:2: DtypeWarning: Columns (0: 층정보) have mixed types. Specify dtype option on import or set low_memory=False.
  store_df = pd.read_csv('../data/processed/base_df.csv', encoding='utf-8')

In [46]:
# 지역별 인구수를 기준으로 내림차순
df_concat_sp.sort_values(by='지역별 인구수', ascending=False)

      지역별 상가수  지역별 인구수
시군구명
천안시     36185   666182
아산시     16271   363678
당진시      9788   172400
서산시      9313   171136
논산시      7097   105977
홍성군      5999   101566
공주시      6759    99757
보령시      6879    91260
예산군      4803    78318
태안군      5185    59039
부여군      3318    57762
금산군      3635    48939
서천군      3168    46761
계룡시      1765    45959
청양군      1661    30051

In [47]:
# 인구가 만명으로 동일할 때 상가수가 어디가 제일 많은지 확인
df_concat_sp['인구 1만명당 상가수'] = (df_concat_sp['지역별 상가수'] / df_concat_sp['지역별 인구수'] * 10000)
df_concat_sp = df_concat_sp.sort_values(by='인구 1만명당 상가수', ascending=False)
df_concat_sp

      지역별 상가수  지역별 인구수  인구 1만명당 상가수
시군구명
태안군      5185    59039   878.233032
보령시      6879    91260   753.780408
금산군      3635    48939   742.761397
공주시      6759    99757   677.546438
서천군      3168    46761   677.487650
논산시      7097   105977   669.673608
예산군      4803    78318   613.268980
홍성군      5999   101566   590.650415
부여군      3318    57762   574.426093
당진시      9788   172400   567.749420
청양군      1661    30051   552.727031
서산시      9313   171136   544.187079
천안시     36185   666182   543.169885
아산시     16271   363678   447.401273
계룡시      1765    45959   384.037947

In [ ]:
# 1. 평균 구하기
mean_store = df_concat_sp['인구 1만명당 상가수'].mean().round(2)
mean_store

np.float64(614.47)

In [ ]:
# Numpy 벡터 연산
import numpy as np
df_concat_sp['평균'] = np.where (
    df_concat_sp['인구 1만명당 상가수'] >= mean_store,
    '평균 이상',
    '평균 이하 '
)

df_concat_sp

      지역별 상가수  지역별 인구수  인구 1만명당 상가수      평균
시군구명
계룡시      1765    45959   384.037947  평균 이하
공주시      6759    99757   677.546438   평균 이상
금산군      3635    48939   742.761397   평균 이상
논산시      7097   105977   669.673608   평균 이상
당진시      9788   172400   567.749420  평균 이하
보령시      6879    91260   753.780408   평균 이상
부여군      3318    57762   574.426093  평균 이하
서산시      9313   171136   544.187079  평균 이하
서천군      3168    46761   677.487650   평균 이상
아산시     16271   363678   447.401273  평균 이하
예산군      4803    78318   613.268980  평균 이하
천안시     36185   666182   543.169885  평균 이하
청양군      1661    30051   552.727031  평균 이하
태안군      5185    59039   878.233032   평균 이상
홍성군      5999   101566   590.650415  평균 이하